### ISSUE TITLE
Node.js Init not working

### ISSUE THREAD

**Issue by ankur108** [rudrakh97/KYC-chain#12]
Excellent work, but when I try doing node init.js, it shows me this error.

internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                ^
Error: /home/ankur/Desktop/KYC-chain-master/root/node_modules/scrypt/build/Release/scrypt.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ankur/Desktop/KYC-chain-master/root/node_modules/scrypt/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

Any help would be appreciated !!!

**Comment by mathewsjose1998** [comment]
I also face the same issue but now its working perfect .Make the node version 10.15.3 and npm version 6.9.0 and go to root folder delete the nodemodules and package-lock.json.
then in terminal run ganache-cli
then install the npm install solc@0.4.26
and  npm install web3@0.20.1 
then do the steps from node init.js  . it works......
