### ISSUE TITLE
web3 error

### ISSUE THREAD

**Issue by indrajeetb** [rudrakh97/KYC-chain#4]
when i execute node init.js i get the following error : 

hp@hp-HP-Notebook ~/kyc/root $ node init.js
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'web3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/hp/kyc/root/init.js:1:74)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

**Comment by rudrakhp** [comment]
Make sure you have the `web3js` module installed. Install it using the command `npm install web3`. Refer [this](https://github.com/ethereum/web3.js/) repo for more.

**Comment by indrajeetb** [comment]
I tried installing web3js using npm install web3 but i was getting some error on my mint. So i switched to ubuntu and the error is fixed. Now when i execute node init.js i get the following error

node init.js
/home/hp/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nod

TypeError: web3.eth.contract is not a function
    at Timeout.afterDelay [as _onTimeout] (/home/hp/kyc/root/init.js:18:28)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

**Comment by indrajeetb** [comment]
I figured out the issue was with the web3, as the current version is unstable. I fixed the error. The index.html opens but i'm not able to sign in. after sign up when i click on login, nothing happens
